CREATE OR REPLACE TRIGGER INSERTED_IN_EMPLOYEE
AFTER INSERT OR DELETE
ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYMENT_LOG
 IF INSERTING
   THEN
       (NEW.EMPLOYEE_ID, NEW.FIRST_NAME, NEW.LAST_NAME, 'HIRED', CURRENT_TIMESTAMP);
   ELSE
       (OLD.EMPLOYEE_ID, OLD.FIRST_NAME, OLD.LAST_NAME, 'FIRED', CURRENT_TIMESTAMP);
   END IF;
END;